
function normalizeTR(s){return (s||"").toLowerCase().replaceAll("ı","i").replaceAll("İ","i").replaceAll("ğ","g").replaceAll("ü","u").replaceAll("ş","s").replaceAll("ö","o").replaceAll("ç","c").normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function getSearchTerm(){return (document.getElementById("bigSearchInput")?.value.trim()) || (document.getElementById("sideSearchInput")?.value.trim()) || ""}
function scoreRecord(r,q){const t=normalizeTR(r.title),a=normalizeTR(r.answer),d=normalizeTR(r.detail),p=normalizeTR(r.people),c=normalizeTR(r.category),dt=normalizeTR(String(r.date||"")),y=String(r.year||""); if(!q)return 1; const words=q.split(/\s+/).filter(Boolean); let s=0; if(t===q)s+=1000;if(p===q)s+=900;if(t.includes(q))s+=540;if(p.includes(q))s+=420;if(a.includes(q))s+=180;if(d.includes(q))s+=80;if(c.includes(q))s+=35;if(dt.includes(q)||y.includes(q))s+=65;words.forEach(w=>{if(t.includes(w))s+=95;if(p.includes(w))s+=90;if(a.includes(w))s+=35;if(d.includes(w))s+=15});return s}
function filterData(){if(!window.NZ_DATA)return[];const q=normalizeTR(getSearchTerm());const type=document.getElementById("typeFilter")?.value||"";const year=document.getElementById("yearFilter")?.value||"";return window.NZ_DATA.map(r=>({r,score:scoreRecord(r,q)})).filter(x=>(!q||x.score>0)&&(!type||x.r.type===type)&&(!year||String(x.r.year)===String(year))).sort((a,b)=>b.score-a.score||b.r.year-a.r.year).map(x=>x.r)}
function renderArchive(){const data=filterData();const box=document.getElementById("archiveList");const count=document.getElementById("archiveCount");if(count)count.textContent=data.length+" kayıt";if(box){box.innerHTML="";data.slice(0,700).forEach(r=>{const a=document.createElement("a");a.className="archive-row";a.href=r.slug;a.innerHTML=`<b>${r.date||r.year}</b><span>${r.type}</span><p><strong>${r.title}</strong><br>${r.answer}</p>`;box.appendChild(a)})}renderBigSearchResults(data)}
function renderBigSearchResults(data){const box=document.getElementById("bigSearchResults");if(!box)return;const q=getSearchTerm().trim();box.innerHTML="";if(q.length<1)return;if(data.length===0){box.innerHTML=`<div class="ai-answer-box"><p><b>${q}</b> için yakın kayıtlar hazırlanıyor.</p><p>Arşivdeki ilgili başlıkları görmek için farklı kelimeler deneyebilirsin.</p></div>`;return}data.slice(0,8).forEach(r=>{const a=document.createElement("a");a.href=r.slug;a.innerHTML=`<b>${r.date||r.year}</b><span>${r.type}</span><p><strong>${r.title}</strong><br>${r.answer}</p>`;box.appendChild(a)})}
function syncSearch(source){const big=document.getElementById("bigSearchInput"),side=document.getElementById("sideSearchInput");if(source==="big"&&side&&big)side.value=big.value;if(source==="side"&&side&&big)big.value=side.value;renderArchive()}
function fillYears(){const sel=document.getElementById("yearFilter");if(!sel||!window.NZ_DATA)return;[...new Set(window.NZ_DATA.map(r=>r.year))].sort((a,b)=>b-a).forEach(y=>{if(![...sel.options].map(o=>o.value).includes(String(y))){const o=document.createElement("option");o.value=y;o.textContent=y;sel.appendChild(o)}})}
function renderTodayBox(){const labelEl=document.getElementById("todayLabel"),titleEl=document.getElementById("todayTitle"),textEl=document.getElementById("todayText");if(!labelEl||!titleEl||!textEl||!window.NZ_TODAY)return;const now=new Date();const key=String(now.getMonth()+1).padStart(2,"0")+"-"+String(now.getDate()).padStart(2,"0");let items=window.NZ_TODAY.filter(x=>x.date===key);if(items.length===0)items=[{label:now.toLocaleDateString("tr-TR",{day:"numeric",month:"long"}),title:"Bugünün arşivi hazırlanıyor",year:"",text:"Bu tarih için kayıt eklendikçe burada otomatik görünür."}];labelEl.textContent=items[0].label;titleEl.textContent="Tarihte bugün ne oldu?";textEl.innerHTML=items.slice(0,4).map(it=>`<span class="today-mini-event"><b>${it.year?it.year+" • ":""}${it.title}</b><small>${it.text}</small></span>`).join("")}
document.addEventListener("DOMContentLoaded",()=>{fillYears();renderArchive();renderTodayBox();document.getElementById("bigSearchInput")?.addEventListener("input",()=>syncSearch("big"));document.getElementById("sideSearchInput")?.addEventListener("input",()=>syncSearch("side"));["typeFilter","yearFilter"].forEach(id=>document.getElementById(id)?.addEventListener("input",renderArchive))});
